build site:
    image: node:latest
    stage: build
    script:
        - cd Fusion101/web
        - yarn
        - yarn build
    artifacts:
        expire_in: 1 week
        paths:
            - dist